export const threadConstants = {
    ADD_POST: 'ADD_POST',
    ADD_THREAD: 'ADD_THREAD',
    RECIEVE_POST: 'RECIEVE_POST',
    DELETE_THREAD: 'DELETE_THREAD',
    NO_MORE_THREADS: 'NO_MORE_THREADS',
    LOAD_THREADS_SUCCESS: 'LOAD_THREADS_SUCCESS',
    LOAD_THREAD_SUCCESS: 'LOAD_THREAD_SUCCESS',
    LOAD_POSTS_SUCCESS: 'LOAD_POSTS_SUCCESS'
};
